selected_rmats_mode: JC
output_root: E:\Project\katana\katana_output
selected_comparison_ids:
- .git
- __pycache__
- build
- img
thresholds:
  splicing_fdr: 0.05
  splicing_dpsi: 0.1
  deg_padj: 0.05
  deg_log2fc: 1.0
  dexseq_qvalue: 0.05
  dtu_qvalue: 0.05
tool_paths:
  jutils: E:\Project\katana\software\Jutils
  rmats2sashimiplot: E:\Project\katana\software\rmats2sashimiplot
  suppa: E:\Project\katana\software\SUPPA
  rscript: C:/Program Files/R/R-4.5.0/bin/Rscript.exe
comparisons:
- comparison_id: .git
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
- comparison_id: __pycache__
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
- comparison_id: build
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
- comparison_id: img
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
- comparison_id: src
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
- comparison_id: wdl
  display_name: null
  rmats_name: null
  deg_name: null
  suppa_name: null
  dexseq_name: null
  dtu_name: null
  quant_name: null
  experiment_group: null
  control_group: null
  source_direction: original
  analysis_direction: original
  reverse_direction: false
isoform_samples: []
